tango_with_django_project/rango/urls.py
app_name = "rango"
from django.conf.urls import url
from rango import views

app_name = "rango"
urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(
        r"^category/(?P<category_name_slug>[\w\-]+)/$",
        views.show_category,
        name="category",
    ),
    url(r"^greet/$", views.greet, name="greet"),
    url(r"^add_category/$", views.add_category, name="add_category"),
    url(r"^register/$",views.register,name="Register"),
    url(r"^login/$",views.user_login,name="Login"),
    url(r"^logout/$",views.user_logout,name="logout")
]

tango_with_django_project/tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views

urlpatterns = [
    url(r"^$", views.index, name="greet"),
    url(r"^rango/", include("rango.urls")),
    url(r"^admin/", admin.site.urls),
   
]

tango_with_django_project/rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=128)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name


class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField(default="www.google.com")
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title


class Userprofile(models.Model):
    user = models.OneToOneField(User)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to="profile_images", blank=True)

    def __str__(self):
        return self.user.username

tango_with_django_project/rango/views.py
from django.http import HttpResponse,Http404,HttpResponseRedirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render
from rango.models import Category, Page
from rango.forms1 import CategoryForm,UserForm,UserprofileForm


def index(request):
    category_list = Category.objects.order_by("-likes")
    pages_view = Page.objects.order_by("-views")
    context_dict = {"categories": category_list, "pages_view": pages_view}
    return render(request, "rango/index.html", context=context_dict)


def greet(request):
    print(request.method)
    print(request.user)
    return HttpResponse("<h1> thsis is greeting</h1>")

@login_required
def show_category(request, category_name_slug):
    context_dict = {}
    try:
        category = Category.objects.get(slug=category_name_slug)
        page = Page.objects.filter(category=category)
        context_dict["pages"] = page
        context_dict["category"] = category
    except Category.DoesNotExist:
        index(request)
        context_dict["category"] = None
        context_dict["pages"] = None

    return render(request, "rango/category.html", context_dict)

@login_required
def add_category(request):
    form = CategoryForm()
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            form_error=form.errors
            print(form.errors)
    else:
        form = CategoryForm()

    return render(request, "rango/add_category.html", {"form": form})

def register(request):
    registered=False
    if request.method=='POST':
        print(request.POST)
        print(request.FILES)
        user_form=UserForm(data=request.POST)
        profile_form=UserprofileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user=user_form.save()
            user.set_password(user.password)
            user.save()
            profile=profile_form.save(commit=False)
            profile.user=user
            if 'picture' in request.FILES:
                profile.picture=request.FILES['picture']
            profile.save()
            registered=True
        else:
            print (user_form.errors,profile_form.errors)
    else:
        user_form=UserForm()
        profile_form=UserprofileForm()
    
    return render(request,"rango/register.html",{"user_form":user_form,"profile_form":profile_form,"registered":registered})

def user_login(request):
    if request.method=="POST":
        username=request.POST.get("username")
        password=request.POST.get("password")
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return index(request)
            else:
                return HttpResponse("YOUR RANGO ACCOUNT IS DISABLED")
        else:
            print("invalid login details:{0},{1}".format(username,password))
            return render(request,"rango/login.html",{"errors":"Invalid login details"})
    else:
        return render(request,"rango/login.html",{})

@login_required
def user_logout(request):
    logout(request)
    return index(request)

tango_with_django_project/templates/rango/add_category.html
{% extends "rango/base.html" %} {% block title_block %} Add Category
{% endblock %}
{% block body_block %}
<h1>Add a Category</h1>
<div>
  <form id="category_form" method="post" action="/rango/add_category/">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="submit" value=" Create Category" />
  </form>
</div>
{% endblock %}

tango_with_django_project/templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>

<head>
    <link href="{% static 'css/rango/footer.css' %}" rel="stylesheet" type="text/css" />
    <title>Rango-
        {% block title_block %}
        How to Tango
        {% endblock %}
    </title>
</head>

<body>
    <h1 style="text-align:center">Hello
        {% if user.is_authenticated  %}
        {{user.username}} !</h1>
    {% else %}
    ! Please Login</h1>
    {% endif %}
    {% block body_block%}

    <!-- Page specifics-->
    <h1>Default Page</h1>
    {% endblock %}
    <div class="footer">
        <div class="footer_about">
            <p class="footer_content">
                <img src=" " alt="logo" /><br />
                Scoolease is a venture led by the student of IIT Roorkee.The team
                works independently to create a strong school network.Our prime motive
                is to ease out the communication with school and make these golden
                days of knowledge a cake walk.<br /><br />2019 All rights reserved.
            </p>
        </div>
        <div class="footer_gettouch">
            <h4>Get in Touch With Us</h4>

            <p class="footer_content">Feel free to contact us anytime.</p>
            <div class="social_links">
                <img src="" alt="twitter" />
                <img src="" alt="googleplus" />
                <img src="" alt="facebook" />
                <img src="" alt="instagram" />
            </div>
        </div>
        <div class="footer_contact">
            <h4>Contact Information</h4>
            <p class="footer_content">
                D-14 Tripti Vihar,Ujjain-456010<br />+91-9425986067,hello@schoolease.in
            </p>
        </div>
    </div>
</body>

</html>

tango_with_django_project/templates/rango/category.html
{% extends "rango/base.html"%} {% load staticfiles %} {% block title_block %}
Category {% endblock %} {% block body_block %}
<div>
  {% if category %}
  <h1>{{ category.name }}</h1>
  {% if pages %}
  <ul>
    {% for p in pages %}
    <li>
      <a href="{{ p.url }}">{{ p.title }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>There are no pages</strong>
  {% endif %} {% else %}
  <strong>The specified category does not exist!</strong>
  {% endif %}
</div>
{% endblock %}

tango_with_django_project/templates/rango/index.html
{% extends "rango/base.html" %}
{% block title_block %}Home{% endblock %}
{% block body_block %}
<h1>Rango says...</h1>
<div>
  {% if user.is_authenticated %}
  <a href="/rango/logout"><button value="LOGOUT">LOGOUT</button></a>
  {% else %}
  <a href="/rango/register">Please Register</a><br />
  <strong><a href="/rango/login">Login</a></strong><br />
  {% endif %}
  hey there partner! <br />
  <strong>Most Liked Categories</strong><br />
  <div>
    {% if categories %}
    <ul>
      {% for c in categories %}
      <li>
        <a href="{%url 'rango:category' c.slug %} " target="_blank">{{ c.name }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <strong> There Are No Category present </strong>
    {% endif %}
  </div>
  <strong>Most Viewed Pages</strong>
  <br />
  <div>
    {% if pages_view %}
    <ul>
      {% for c in pages_view %}
      <li>
        <a href="{{ c.url }} " target="_blank">{{ c.title }}</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <strong> There Are No Category present </strong>
    {% endif %}
  </div>
  <div><a href="{% url 'rango:add_category' %}"> Add Category</a></div>
</div>
{% endblock %}

tango_with_django_project/templates/rango/login.html
{% extends "rango/base.html" %} {% load staticfiles %} {% block title_block %}
Rango-Login {% endblock %} {% block body_block %}
<h1>Login To Rango</h1>
<img src="{% static 'images/adity.jpg' %}" />
<form action="." method="POST" id="login_form">
  {% csrf_token %}
  <strong> {{ errors }}</strong>
  <br />
  Username: <input type="text" name="username" value="" size="50" />
  <br />
  Password: <input type="password" name="password" value="" size="50" />
  <br />
  <input type="submit" value="submit" />
</form>
{% endblock %}

tango_with_django_project/templates/rango/register.html
{% extends "rango/base.html" %}
{% load staticfiles %}
{% block title_block %}
Register-Tango
{% endblock %}
{% block body_block %}
<h1>Register</h1>
{% if registered %}
<strong> Thank you for registering !</strong>
<a href="/rango/">Return to homepage</a><br />
{% else %}
<strong> Register Here !</strong><br />
<form id="user_form" method="POST" action="/rango/register/" enctype="multipart/form-data">
    {% csrf_token %}
    {{user_form.as_p}}
    {{profile_form.as_p}}
    <input type="submit" value="Register" name="Submit" /> </form>
{% endif %}
{% endblock %}